name: Rust CI

on:
  push:
    branches:
      - main
  
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crate: 
          - collections
          - enums
          - HelloWorld
          - guessing-game
          - restaurant
          - slices
          - structs
          - variables

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and Test ${{ matrix.crate }}
      working-directory: ${{ matrix.crate }}
      run: |
        cargo build --verbose
        cargo test --verbose
