name: Rust CI

on:
  push:
    branches:
      - main
  
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crate: [HelloWorld, guessing-game, slices, variables]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and Test ${{ matrix.crate }}
      working-directory: ${{ matrix.crate }}
      run: |
        cargo build --verbose
        cargo test --verbose

  workspace-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Workspace Build and Test
      run: |
        cargo build --workspace --verbose
        cargo test --workspace --verbose

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings
